project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://ksingh1994.github.io/my_blog/ # you must change this appropriately for RSS feeds to work properly
  title: "myblog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



